// ============================================================
// GENERADO AUTOMATICAMENTE DESDE GOOGLE SHEETS PARA GITHUB
// Última actualización: 26/3/2026, 09:31:49
// ============================================================
var MASTER_FECHA_LISTA = "AMBA - Marzo 2026";
var MASTER_PRODUCTOS = [
    {
        "Art": "2",
        "Categoria": "QUESOS BLANDOS AZULES",
        "Producto": "Queso Azul",
        "Marca": "La Quesera",
        "Presentacion": "Caja por 4 Hormas de 2.4 kg c/u aprox.",
        "UnidxBulto": 4,
        "PrecioLista": 14283.79,
        "Bonif": 30,
        "PrecioBonificado": 18298.65,
        "PesoKg": 1
    },
    {
        "Art": "6",
        "Categoria": "QUESOS BLANDOS AZULES",
        "Producto": "Queso Azul en mitades",
        "Marca": "La Quesera",
        "Presentacion": "Caja por 8 Medias Hormas de 1.2 kg c/u aprox.",
        "UnidxBulto": 8,
        "PrecioLista": 13698.51,
        "Bonif": 30,
        "PrecioBonificado": 9588.96,
        "PesoKg": 1
    },
    {
        "Art": "62",
        "Categoria": "QUESOS BLANDOS AZULES",
        "Producto": "Queso Azul",
        "Marca": "Shehuen",
        "Presentacion": "Caja por 4 Hormas de 2.4 kg c/u aprox.",
        "UnidxBulto": 4,
        "PrecioLista": 11955.41,
        "Bonif": 30,
        "PrecioBonificado": 8368.79,
        "PesoKg": 1
    },
    {
        "Art": "62",
        "Categoria": "QUESOS BLANDOS AZULES",
        "Producto": "Queso Azul",
        "Marca": "Shehuen",
        "Presentacion": "Caja por 4 Hormas de 2.4 kg c/u aprox.",
        "UnidxBulto": 4,
        "PrecioLista": 11955.41,
        "Bonif": 30,
        "PrecioBonificado": 8368.79,
        "PesoKg": 1
    },
    {
        "Art": "60",
        "Categoria": "QUESOS BLANDOS AZULES",
        "Producto": "Queso Azul",
        "Marca": "J.C.",
        "Presentacion": "Caja por 4 Hormas de 2.4 kg c/u aprox.",
        "UnidxBulto": 4,
        "PrecioLista": 13283.79,
        "Bonif": 30,
        "PrecioBonificado": 9298.65,
        "PesoKg": 1
    },
    {
        "Art": "5",
        "Categoria": "QUESOS BLANDOS",
        "Producto": "Queso Cremoso",
        "Marca": "La Quesera",
        "Presentacion": "Caja por 4 Unidades de 4.1 kg c/u aprox.",
        "UnidxBulto": 4,
        "PrecioLista": 10184.32,
        "Bonif": 30,
        "PrecioBonificado": 0,
        "PesoKg": 1
    },
    {
        "Art": "162",
        "Categoria": "QUESOS BLANDOS",
        "Producto": "Queso Mozzarella",
        "Marca": "La Quesera",
        "Presentacion": "Caja por 4 Unidades de 5.0 kg c/u aprox.",
        "UnidxBulto": 4,
        "PrecioLista": 13293.27,
        "Bonif": 30,
        "PrecioBonificado": 9305.29,
        "PesoKg": 5
    },
    {
        "Art": "354",
        "Categoria": "QUESOS DUROS",
        "Producto": "Queso Sardo Fresco",
        "Marca": "J.C.",
        "Presentacion": "Caja por 4 Hormas de 4.0 kg c/u aprox.",
        "UnidxBulto": 4,
        "PrecioLista": 15658.85,
        "Bonif": 36.95,
        "PrecioBonificado": 0,
        "PesoKg": 4
    },
    {
        "Art": "140",
        "Categoria": "QUESOS DUROS",
        "Producto": "Sardo Estacionado (sin pintar)",
        "Marca": "La Quesera",
        "Presentacion": "Caja por 4 Hormas de 3.6 kg c/u aprox.",
        "UnidxBulto": 4,
        "PrecioLista": 17824.06,
        "Bonif": 30,
        "PrecioBonificado": 12476.84,
        "PesoKg": 1
    },
    {
        "Art": "136",
        "Categoria": "QUESOS DUROS",
        "Producto": "Sardo Estacionado (pintado)",
        "Marca": "La Quesera",
        "Presentacion": "Caja por 4 Hormas de 3.7 kg c/u aprox.",
        "UnidxBulto": 4,
        "PrecioLista": 18337.58,
        "Bonif": 30,
        "PrecioBonificado": 12836.31,
        "PesoKg": 1
    },
    {
        "Art": "355",
        "Categoria": "QUESOS DUROS",
        "Producto": "Queso Romanito (sin pintar)",
        "Marca": "La Quesera",
        "Presentacion": "Caja por 4 Hormas de 4.3 kg c/u aprox.",
        "UnidxBulto": 4,
        "PrecioLista": 17904.61,
        "Bonif": 30,
        "PrecioBonificado": 12533.23,
        "PesoKg": 1
    },
    {
        "Art": "356",
        "Categoria": "QUESOS DUROS",
        "Producto": "Queso Romanito (pintado)",
        "Marca": "La Quesera",
        "Presentacion": "Caja por 4 Hormas de 4.3 kg c/u aprox.",
        "UnidxBulto": 4,
        "PrecioLista": 18482.05,
        "Bonif": 30,
        "PrecioBonificado": 12937.44,
        "PesoKg": 1
    },
    {
        "Art": "137",
        "Categoria": "QUESOS DUROS",
        "Producto": "Queso Sbrinz",
        "Marca": "La Quesera",
        "Presentacion": "Caja por 2 Hormas de 8.5 kg c/u aprox.",
        "UnidxBulto": 2,
        "PrecioLista": 18482.05,
        "Bonif": 30,
        "PrecioBonificado": 12937.44,
        "PesoKg": 1
    },
    {
        "Art": "138",
        "Categoria": "QUESOS DUROS",
        "Producto": "Reggianito",
        "Marca": "La Quesera",
        "Presentacion": "Caja por 2 Hormas de 8.5 kg c/u aprox.",
        "UnidxBulto": 2,
        "PrecioLista": 19043.32,
        "Bonif": 30,
        "PrecioBonificado": 13330.32,
        "PesoKg": 1
    },
    {
        "Art": "358",
        "Categoria": "QUESOS DUROS",
        "Producto": "Queso Provolone (sin pintar)",
        "Marca": "La Quesera",
        "Presentacion": "Caja por 2 Hormas de 6.1 kg c/u aprox.",
        "UnidxBulto": 2,
        "PrecioLista": 21016.33,
        "Bonif": 30,
        "PrecioBonificado": 14711.43,
        "PesoKg": 1
    },
    {
        "Art": "359",
        "Categoria": "QUESOS DUROS",
        "Producto": "Queso Provolone (pintado)",
        "Marca": "La Quesera",
        "Presentacion": "Caja por 2 Hormas de 6.1 kg c/u aprox.",
        "UnidxBulto": 2,
        "PrecioLista": 21656.36,
        "Bonif": 30,
        "PrecioBonificado": 15159.45,
        "PesoKg": 1
    },
    {
        "Art": "361",
        "Categoria": "QUESOS DUROS",
        "Producto": "Queso Parmesano",
        "Marca": "La Quesera",
        "Presentacion": "Caja por 1 Horma de 12.5 kg aprox.",
        "UnidxBulto": 1,
        "PrecioLista": 22144.93,
        "Bonif": 30,
        "PrecioBonificado": 15501.45,
        "PesoKg": 1
    },
    {
        "Art": "360",
        "Categoria": "QUESOS DUROS",
        "Producto": "Canestrato con Pimienta (Pintado)",
        "Marca": "La Quesera",
        "Presentacion": "Caja por 2 Hormas de 3.8 kg c/u aprox.",
        "UnidxBulto": 2,
        "PrecioLista": 21353.03,
        "Bonif": 30,
        "PrecioBonificado": 14947.12,
        "PesoKg": 1
    },
    {
        "Art": "357",
        "Categoria": "QUESOS DUROS",
        "Producto": "Queso Provoleta",
        "Marca": "La Quesera",
        "Presentacion": "Caja por 4 Hormas de 3.8 kg c/u aprox.",
        "UnidxBulto": 4,
        "PrecioLista": 17262.64,
        "Bonif": 30,
        "PrecioBonificado": 12083.85,
        "PesoKg": 1
    },
    {
        "Art": "151",
        "Categoria": "QUESOS SEMI-DUROS C/OJOS",
        "Producto": "Queso Gruyere",
        "Marca": "La Quesera",
        "Presentacion": "Hormas de 42.0 kg aprox.",
        "UnidxBulto": 1,
        "PrecioLista": 20698.43,
        "Bonif": 30,
        "PrecioBonificado": 14488.9,
        "PesoKg": 42
    },
    {
        "Art": "149",
        "Categoria": "QUESOS SEMI-DUROS C/OJOS",
        "Producto": "Queso Gruyere (en mitades)",
        "Marca": "La Quesera",
        "Presentacion": "Fraccionado en Mitades de 21.0 kg aprox.",
        "UnidxBulto": 1,
        "PrecioLista": 21205.25,
        "Bonif": 30,
        "PrecioBonificado": 14843.68,
        "PesoKg": 21
    },
    {
        "Art": "169",
        "Categoria": "QUESOS SEMI-DUROS C/OJOS",
        "Producto": "Queso Gruyere Fraccionado",
        "Marca": "La Quesera",
        "Presentacion": "Caja por 4 Cunas de 3.5 kg c/u aprox.",
        "UnidxBulto": 4,
        "PrecioLista": 22079.56,
        "Bonif": 30,
        "PrecioBonificado": 15455.69,
        "PesoKg": 1
    },
    {
        "Art": "362",
        "Categoria": "QUESOS SEMI-DUROS C/OJOS",
        "Producto": "Queso Gruyere Fraccionado",
        "Marca": "Shehuen",
        "Presentacion": "Caja por 4 Cunas de 3.5 kg c/u aprox.",
        "UnidxBulto": 4,
        "PrecioLista": 19054.97,
        "Bonif": 30,
        "PrecioBonificado": 13338.48,
        "PesoKg": 1
    },
    {
        "Art": "18",
        "Categoria": "QUESOS SEMI-DUROS C/OJOS",
        "Producto": "Queso Gruyerito",
        "Marca": "La Quesera",
        "Presentacion": "Hormas de 13.0 kg aprox.",
        "UnidxBulto": 1,
        "PrecioLista": 19054.97,
        "Bonif": 30,
        "PrecioBonificado": 13338.48,
        "PesoKg": 13
    },
    {
        "Art": "335",
        "Categoria": "QUESOS SEMI-DUROS C/OJOS",
        "Producto": "Queso Gruyerito Fraccionado",
        "Marca": "La Quesera",
        "Presentacion": "Caja por 4 Cunas de 3.2 kg c/u aprox.",
        "UnidxBulto": 4,
        "PrecioLista": 20593.21,
        "Bonif": 30,
        "PrecioBonificado": 14415.25,
        "PesoKg": 1
    },
    {
        "Art": "174",
        "Categoria": "QUESOS SEMI-DUROS C/OJOS",
        "Producto": "Queso Gruyerito",
        "Marca": "Shehuen",
        "Presentacion": "Hormas de 13.0 kg aprox.",
        "UnidxBulto": 1,
        "PrecioLista": 17149.47,
        "Bonif": 30,
        "PrecioBonificado": 12004.63,
        "PesoKg": 13
    },
    {
        "Art": "336",
        "Categoria": "QUESOS SEMI-DUROS C/OJOS",
        "Producto": "Queso Gruyerito fraccionado",
        "Marca": "Shehuen",
        "Presentacion": "Caja por 4 Cunas de 3.2 kg c/u aprox.",
        "UnidxBulto": 4,
        "PrecioLista": 18530.84,
        "Bonif": 30,
        "PrecioBonificado": 12971.59,
        "PesoKg": 1
    },
    {
        "Art": "23",
        "Categoria": "RALLADOS",
        "Producto": "Rallado x 8 g.",
        "Marca": "La Quesera",
        "Presentacion": "Caja con 6 Displays de 100 sobres c/u.",
        "UnidxBulto": 6,
        "PrecioLista": 14326.18,
        "Bonif": 30,
        "PrecioBonificado": 10028.33,
        "PesoKg": 1
    },
    {
        "Art": "24",
        "Categoria": "RALLADOS",
        "Producto": "Rallado x 40 g.",
        "Marca": "La Quesera",
        "Presentacion": "Caja con 6 Displays de 20 sobres c/u.",
        "UnidxBulto": 6,
        "PrecioLista": 11265.72,
        "Bonif": 30,
        "PrecioBonificado": 7886,
        "PesoKg": 1
    },
    {
        "Art": "25",
        "Categoria": "RALLADOS",
        "Producto": "Rallado x 100 g.",
        "Marca": "La Quesera",
        "Presentacion": "Caja con 50 sobres c/u.",
        "UnidxBulto": 50,
        "PrecioLista": 1329.63,
        "Bonif": 30,
        "PrecioBonificado": 930.74,
        "PesoKg": 1
    },
    {
        "Art": "26",
        "Categoria": "RALLADOS",
        "Producto": "Rallado x 150 g.",
        "Marca": "La Quesera",
        "Presentacion": "Caja con 40 sobres c/u.",
        "UnidxBulto": 40,
        "PrecioLista": 1903.42,
        "Bonif": 30,
        "PrecioBonificado": 1332.39,
        "PesoKg": 1
    },
    {
        "Art": "27",
        "Categoria": "RALLADOS",
        "Producto": "Rallado x 1 kg.",
        "Marca": "La Quesera",
        "Presentacion": "Caja con 10 bolsas c/u.",
        "UnidxBulto": 10,
        "PrecioLista": 11642.77,
        "Bonif": 30,
        "PrecioBonificado": 8149.94,
        "PesoKg": 1
    },
    {
        "Art": "28",
        "Categoria": "RALLADOS",
        "Producto": "Rallado x 3 kg.",
        "Marca": "La Quesera",
        "Presentacion": "Caja con 4 bolsas c/u.",
        "UnidxBulto": 4,
        "PrecioLista": 11450.39,
        "Bonif": 30,
        "PrecioBonificado": 8015.27,
        "PesoKg": 3
    },
    {
        "Art": "184",
        "Categoria": "QUESOS PROCESADOS",
        "Producto": "Barra Mixto con Salame",
        "Marca": "La Quesera",
        "Presentacion": "Caja por 4 unidades de 2.8 kg c/u aprox.",
        "UnidxBulto": 4,
        "PrecioLista": 12452.26,
        "Bonif": 30,
        "PrecioBonificado": 8716.58,
        "PesoKg": 1
    },
    {
        "Art": "349",
        "Categoria": "QUESOS PROCESADOS",
        "Producto": "Queso Cheddar para Untar",
        "Marca": "Shehuen",
        "Presentacion": "Caja con 4 Pouch de 4 kg c/u.",
        "UnidxBulto": 4,
        "PrecioLista": 7007.83,
        "Bonif": 30,
        "PrecioBonificado": 4905.48,
        "PesoKg": 4
    },
    {
        "Art": "168",
        "Categoria": "QUESOS PROCESADOS",
        "Producto": "Queso Cheddar Barra",
        "Marca": "La Quesera",
        "Presentacion": "Caja por 4 Hormas de 2.8 kg c/u aprox.",
        "UnidxBulto": 4,
        "PrecioLista": 14897.78,
        "Bonif": 30,
        "PrecioBonificado": 10428.45,
        "PesoKg": 1
    },
    {
        "Art": "484",
        "Categoria": "QUESOS PROCESADOS",
        "Producto": "Pasta Azul",
        "Marca": "La Quesera",
        "Presentacion": "Caja con 4 Pouch de 3 kg c/u.",
        "UnidxBulto": 4,
        "PrecioLista": 11246.63,
        "Bonif": 30,
        "PrecioBonificado": 7872.64,
        "PesoKg": 3
    },
    {
        "Art": "483",
        "Categoria": "QUESOS PROCESADOS",
        "Producto": "Queso Crema",
        "Marca": "Shehuen",
        "Presentacion": "Caja con 4 Pouch de 3 kg c/u.",
        "UnidxBulto": 4,
        "PrecioLista": 8147.19,
        "Bonif": 30,
        "PrecioBonificado": 0,
        "PesoKg": 3
    },
    {
        "Art": "482",
        "Categoria": "QUESOS PROCESADOS",
        "Producto": "Queso Crema",
        "Marca": "La Quesera",
        "Presentacion": "Caja con 4 Pouch de 3 kg c/u.",
        "UnidxBulto": 4,
        "PrecioLista": 7185.13,
        "Bonif": 30,
        "PrecioBonificado": 5029.59,
        "PesoKg": 3
    },
    {
        "Art": "450",
        "Categoria": "QUESOS PROCESADOS UNTABLES",
        "Producto": "Queso Crema Clasico",
        "Marca": "La Quesera",
        "Presentacion": "Caja por 12 unidades de 290 g c/u.",
        "UnidxBulto": 12,
        "PrecioLista": 1527.25,
        "Bonif": 25,
        "PrecioBonificado": 1145.44,
        "PesoKg": 1
    },
    {
        "Art": "451",
        "Categoria": "QUESOS PROCESADOS UNTABLES",
        "Producto": "Queso Crema Light",
        "Marca": "La Quesera",
        "Presentacion": "Caja por 12 unidades de 290 g c/u.",
        "UnidxBulto": 12,
        "PrecioLista": 1527.25,
        "Bonif": 25,
        "PrecioBonificado": 1145.44,
        "PesoKg": 1
    },
    {
        "Art": "489",
        "Categoria": "QUESOS PROCESADOS UNTABLES",
        "Producto": "Queso Untable Azul",
        "Marca": "La Quesera",
        "Presentacion": "Caja por 12 unidades de 180 g c/u.",
        "UnidxBulto": 12,
        "PrecioLista": 1288.27,
        "Bonif": 22,
        "PrecioBonificado": 1004.85,
        "PesoKg": 1
    },
    {
        "Art": "491",
        "Categoria": "QUESOS PROCESADOS UNTABLES",
        "Producto": "Queso Untable Clasico",
        "Marca": "La Quesera",
        "Presentacion": "Caja por 12 unidades de 180 g c/u.",
        "UnidxBulto": 12,
        "PrecioLista": 1288.27,
        "Bonif": 22,
        "PrecioBonificado": 1004.85,
        "PesoKg": 1
    },
    {
        "Art": "492",
        "Categoria": "QUESOS PROCESADOS UNTABLES",
        "Producto": "Queso Untable Gruyere",
        "Marca": "La Quesera",
        "Presentacion": "Caja por 12 unidades de 180 g c/u.",
        "UnidxBulto": 12,
        "PrecioLista": 1288.27,
        "Bonif": 22,
        "PrecioBonificado": 1004.85,
        "PesoKg": 1
    },
    {
        "Art": "493",
        "Categoria": "QUESOS PROCESADOS UNTABLES",
        "Producto": "Queso Untable Jamon",
        "Marca": "La Quesera",
        "Presentacion": "Caja por 12 unidades de 180 g c/u.",
        "UnidxBulto": 12,
        "PrecioLista": 1288.27,
        "Bonif": 22,
        "PrecioBonificado": 1004.85,
        "PesoKg": 1
    },
    {
        "Art": "488",
        "Categoria": "MANTECAS",
        "Producto": "Manteca",
        "Marca": "La Quesera",
        "Presentacion": "Caja con 8 Pilones de 2.5 kg.",
        "UnidxBulto": 8,
        "PrecioLista": 11910.94,
        "Bonif": 30,
        "PrecioBonificado": 8337.66,
        "PesoKg": 1
    },
    {
        "Art": "488",
        "Categoria": "MANTECAS NUEVA",
        "Producto": "Manteca",
        "Marca": "La Quesera",
        "Presentacion": "Caja con 8 Pilones de 2.5 kg.",
        "UnidxBulto": 8,
        "PrecioLista": 11910.94,
        "Bonif": 30,
        "PrecioBonificado": 9337.66,
        "PesoKg": 1
    }
];
